baseURL = "https://hpcde.github.io/"
languageCode = "en-us"
title = "HPCDE lab"
theme = "foundation-theme"
canonifyURLs = true

[markup.goldmark.renderer]
    #   hardWraps = true
      unsafe = true
    #   xhtml = true

SectionPagesMenu = ["main", "social"]

[params]
custom_css = ["css/custom.css"]

[params.meta]
description = "北京科技大学高性能计算与数据工程实验室"
keywords = "USTB, AI, hpc, developer"

[params.footer]
address= "北京科技大学机电信息楼 1220"

[params.hero]
herotitle = "Welcome to HPCDE lab"
herodiscription = "欢迎访问北京科技大学高性能计算与数据工程实验室"
btnblue = "研究方向"
btngreen = "最新进展"


[params.main]
contentOneTitle = "动态"
contentTwoTitle = "简介"
contentOneBody = """
1. 2022年11月，恭喜实验室团队在第三届“[先导杯](https://cas-pra.sugon.com)”计算应用大奖赛中分别获得一项一等奖和一项二等奖。
2. 2012年10月，李士刚论文“Asynchronous Work Stealing on Distributed Memory Systems”被PDP 2013（21st Euromicro International Conference on Parallel, Distributed, and Network-Based Processing）国际会议录用。  
3. 2012年9月，欢迎新同学（张吉群、沙超群、贾丽娜、方明哲、傅全权、曾婉姝、王道沁、许文文）加盟实验室  
4. 2012年8月，林薇、牛嵘霞等开题  
[更多](/news)
"""

contentTwoBody = """
北京科技大学**高性能计算与数据工程实验室**（High Performance Computing and Data Engineering Lab, HPC&DE Labs）成立于2004年。
现有教授2人，副教授3人，讲师2人，博士后2人。实验室面积近300平方米，具有以万亿次高性能计算机和64核高性能服务器为代表硬件设备和以Oracle数据库管理系统等为代表的大型软件开发工具。设备资产价值400多万元。
[更多](/p/introduce)
"""


[[menu.main]]
name = "新闻动态"
url = "/news"

[[menu.main]]
name = "团队人员"
url = "/team"

[[menu.main]]
name = "开源项目"
url = "/p/open_source"

[[menu.main]]
name = "项目支持"
url = "/p/projects"

[[menu.main]]
name = "研究方向"
url = "/p/interests"

[[menu.main]]
name = "科研成果"
url = "/p/publications"

[[menu.social]]
name = "计算机与通信工程学院"
url = "http://scce.ustb.edu.cn"

[[menu.social]]
name = "智能超算融合应用技术教育部工程研究中心"
url = "http://ercis.ustb.edu.cn"

[[menu.social]]
name = "Team on Github"
url = "https://github.com/hpcde"
